#!/usr/bin/env node

import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { Keypair } from '@stellar/stellar-sdk'

type BootstrapIdentity = {
  label: string
  secretKey: string
  publicKey: string
}

type ParsedArgs = {
  command: string
  dryRun: boolean
  shouldFund: boolean
  shouldGenerateFeeSponsor: boolean
  envFile: string
}

function parseArgs(argv: string[]): ParsedArgs {
  const args = [...argv]
  const first = args[0]
  const command = first && !first.startsWith('--') ? args.shift() ?? 'bootstrap' : 'bootstrap'
  let envFile = '.env.local'

  for (let index = 0; index < args.length; index += 1) {
    if (args[index] === '--env-file' && args[index + 1]) {
      envFile = args[index + 1]
      break
    }
  }

  return {
    command,
    dryRun: args.includes('--dry-run'),
    shouldFund: args.includes('--friendbot'),
    shouldGenerateFeeSponsor: args.includes('--fee-sponsor'),
    envFile,
  }
}

function parseEnv(text: string) {
  const parsed = new Map<string, string>()
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) {
      continue
    }

    const index = line.indexOf('=')
    if (index === -1) {
      continue
    }

    parsed.set(line.slice(0, index), line.slice(index + 1))
  }

  return parsed
}

async function loadEnvMap(envFile: string) {
  if (!existsSync(envFile)) {
    return new Map<string, string>()
  }

  return parseEnv(await readFile(envFile, 'utf8'))
}

function ensureIdentity(env: Map<string, string>, keyName: string, label: string): BootstrapIdentity {
  const existingSecret = env.get(keyName)
  const keypair = existingSecret ? Keypair.fromSecret(existingSecret) : Keypair.random()
  env.set(keyName, keypair.secret())
  return {
    label,
    secretKey: keypair.secret(),
    publicKey: keypair.publicKey(),
  }
}

async function friendbotFund(account: BootstrapIdentity) {
  const response = await fetch(
    `https://friendbot.stellar.org/?addr=${encodeURIComponent(account.publicKey)}`,
  )
  if (!response.ok) {
    throw new Error(`Friendbot funding failed for ${account.label}: ${response.status}`)
  }
  console.log(`[xMPP bootstrap] funded ${account.label} ${account.publicKey}`)
}

async function writeEnvFile(envFile: string, env: Map<string, string>) {
  const lines = ['# Generated by xmpp-demo bootstrap']
  for (const [key, value] of [...env.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`${key}=${value}`)
  }
  lines.push('')
  await writeFile(envFile, lines.join('\n'), 'utf8')
}

async function bootstrap(args: ParsedArgs) {
  const envFile = resolve(process.cwd(), args.envFile)
  const env = await loadEnvMap(envFile)

  const agent = ensureIdentity(env, 'XMPP_AGENT_SECRET_KEY', 'agent')
  const facilitator = ensureIdentity(env, 'FACILITATOR_STELLAR_PRIVATE_KEY', 'facilitator')
  const mppServer = ensureIdentity(env, 'MPP_SECRET_KEY', 'mpp-server')

  env.set('X402_RECIPIENT_ADDRESS', env.get('X402_RECIPIENT_ADDRESS') || facilitator.publicKey)
  env.set('MPP_RECIPIENT_ADDRESS', env.get('MPP_RECIPIENT_ADDRESS') || mppServer.publicKey)

  let feeSponsor: BootstrapIdentity | null = null
  if (args.shouldGenerateFeeSponsor) {
    feeSponsor = ensureIdentity(env, 'XMPP_MPP_FEE_SPONSOR_SECRET_KEY', 'mpp-fee-sponsor')
    env.set('XMPP_ENABLE_MPP_FEE_SPONSORSHIP', 'true')
    env.set('XMPP_ENABLE_MPP_CHARGE_FEE_SPONSORSHIP', 'false')
    env.set('XMPP_ENABLE_MPP_SESSION_FEE_SPONSORSHIP', 'true')
  }

  if (!args.dryRun) {
    await writeEnvFile(envFile, env)
    console.log(`[xMPP bootstrap] wrote ${envFile}`)
  } else {
    console.log('[xMPP bootstrap] dry run only; no files were modified')
  }

  console.log(`[xMPP bootstrap] agent        ${agent.publicKey}`)
  console.log(`[xMPP bootstrap] facilitator  ${facilitator.publicKey}`)
  console.log(`[xMPP bootstrap] mpp-server   ${mppServer.publicKey}`)
  if (feeSponsor) {
    console.log(`[xMPP bootstrap] fee-sponsor ${feeSponsor.publicKey}`)
  }

  if (args.shouldFund && !args.dryRun) {
    await friendbotFund(agent)
    await friendbotFund(facilitator)
    await friendbotFund(mppServer)
    if (feeSponsor) {
      await friendbotFund(feeSponsor)
    }
  }

  console.log('[xMPP bootstrap] next steps:')
  console.log(`  export $(grep -v '^#' ${args.envFile} | xargs)`)
  console.log('  set XMPP_POLICY_CONTRACT_ID and XMPP_SESSION_REGISTRY_CONTRACT_ID if you want contract-backed policy and session state')
  console.log('  start the xMPP gateway or point XmppGatewayClient at an existing deployment')
}

function printHelp() {
  console.log('xMPP SDK CLI')
  console.log('')
  console.log('Usage:')
  console.log('  xmpp-demo bootstrap [--dry-run] [--friendbot] [--fee-sponsor] [--env-file .env.local]')
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  if (args.command === '--help' || args.command === 'help') {
    printHelp()
    return
  }

  if (args.command !== 'bootstrap') {
    throw new Error(`Unsupported xMPP CLI command: ${args.command}`)
  }

  await bootstrap(args)
}

main().catch((error) => {
  console.error('[xMPP bootstrap] failed', error)
  process.exit(1)
})
