import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { hash, Keypair, nativeToScVal, rpc } from '@stellar/stellar-sdk'
import { AssembledTransaction, basicNodeSigner } from '@stellar/stellar-sdk/contract'
import { Client as SmartAccountClient } from 'smart-account-kit-bindings'
import { config } from '../packages/config/src/index.js'
import { getEffectiveSmartAccountFeeCeiling, SMART_ACCOUNT_MIN_TRANSACTION_FEE_STROOPS } from '../packages/wallet/src/index.js'

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const envLocalPath = resolve(repoRoot, '.env.local')
const dryRun = process.argv.includes('--dry-run')
const checkOnly = process.argv.includes('--check')
const force = process.argv.includes('--force')
const shouldFund = process.argv.includes('--fund')
const USDC_TESTNET_CONTRACT_ID = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC'
const DEFAULT_TOP_UP_STROOPS = BigInt(10_000_000)

function parseEnv(text: string) {
  const parsed = new Map<string, string>()
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) {
      continue
    }

    const index = line.indexOf('=')
    if (index === -1) {
      continue
    }

    parsed.set(line.slice(0, index), line.slice(index + 1))
  }

  return parsed
}

async function loadEnvLocal() {
  const content = existsSync(envLocalPath) ? await readFile(envLocalPath, 'utf8') : ''
  return parseEnv(content)
}

async function writeEnvLocal(env: Map<string, string>) {
  const lines = ['# Generated by xMPP bootstrap scripts']
  for (const [key, value] of [...env.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`${key}=${value}`)
  }
  lines.push('')
  await writeFile(envLocalPath, lines.join('\n'), 'utf8')
}

function getAgentKeypair() {
  if (!config.wallet.agentSecretKey) {
    throw new Error('XMPP_AGENT_SECRET_KEY is required before bootstrapping a smart account.')
  }

  return Keypair.fromSecret(config.wallet.agentSecretKey)
}

async function deployDelegatedSmartAccount(agent: Keypair) {
  const deployTx = await SmartAccountClient.deploy(
    {
      signers: [createDelegatedSigner(agent.publicKey())],
      policies: new Map(),
    },
    {
      networkPassphrase: config.networkPassphrase,
      rpcUrl: config.rpcUrl,
      wasmHash: config.wallet.smartAccountWasmHash,
      publicKey: agent.publicKey(),
      salt: hash(Buffer.from(`xmpp-smart-account:${agent.publicKey()}`)),
      timeoutInSeconds: 30,
    },
  )

  const sent = await deployTx.signAndSend({
    signTransaction: basicNodeSigner(agent, config.networkPassphrase).signTransaction,
  })

  const contractId =
    sent.result && typeof sent.result === 'object' && 'options' in sent.result
      ? ((sent.result as { options?: { contractId?: string } }).options?.contractId ?? null)
      : null

  if (!contractId) {
    throw new Error('Smart account deploy succeeded but no contract id was returned.')
  }

  return {
    contractId,
    hash: sent.sendTransactionResponse?.hash ?? null,
  }
}

function createDelegatedSigner(publicKey: string) {
  return {
    tag: 'Delegated' as const,
    values: [publicKey] as const,
  }
}

async function inspectRpcHealth() {
  try {
    const server = new rpc.Server(config.rpcUrl)
    const latestLedger = await server.getLatestLedger()
    return {
      reachable: true,
      latestLedger: latestLedger.sequence,
      error: null,
    }
  } catch (error) {
    return {
      reachable: false,
      latestLedger: null,
      error: error instanceof Error ? error.message : 'unknown rpc error',
    }
  }
}

function parseKeyStatus(secret?: string) {
  if (!secret) {
    return { configured: false, publicKey: null, error: 'missing' }
  }

  try {
    return {
      configured: true,
      publicKey: Keypair.fromSecret(secret).publicKey(),
      error: null,
    }
  } catch (error) {
    return {
      configured: true,
      publicKey: null,
      error: error instanceof Error ? error.message : 'invalid secret',
    }
  }
}

async function buildBootstrapStatus(contractId?: string | null) {
  const configured = Boolean(contractId)
  const rpcHealth = await inspectRpcHealth()
  const agentKey = parseKeyStatus(config.wallet.agentSecretKey)
  const facilitatorKey = parseKeyStatus(config.x402.facilitatorPrivateKey)
  const preflightFailures = [
    !contractId ? 'XMPP_SMART_ACCOUNT_CONTRACT_ID' : null,
    !agentKey.configured ? 'XMPP_AGENT_SECRET_KEY' : null,
    agentKey.error && agentKey.error !== 'missing' ? 'XMPP_AGENT_SECRET_KEY_INVALID' : null,
    !facilitatorKey.configured ? 'FACILITATOR_STELLAR_PRIVATE_KEY' : null,
    facilitatorKey.error && facilitatorKey.error !== 'missing'
      ? 'FACILITATOR_STELLAR_PRIVATE_KEY_INVALID'
      : null,
    !rpcHealth.reachable ? 'XMPP_RPC_UNREACHABLE' : null,
  ].filter((value): value is string => value !== null)

  return {
    configured,
    routeCoverage: configured ? 'x402-only' : 'inactive',
    demoReady: configured && preflightFailures.length === 0,
    mppBacked: false,
    unsupportedReason:
      configured
        ? 'MPP charge and MPP session remain explicit Keypair flows in the current client stack.'
        : null,
    configuredMaxTransactionFeeStroops: config.x402.maxTransactionFeeStroops,
    effectiveMaxTransactionFeeStroops: getEffectiveSmartAccountFeeCeiling(),
    feeFloorApplied:
      configured && config.x402.maxTransactionFeeStroops < SMART_ACCOUNT_MIN_TRANSACTION_FEE_STROOPS,
    preflightFailures,
    keys: {
      agent: agentKey,
      facilitator: facilitatorKey,
    },
    rpc: rpcHealth,
    contracts: {
      smartAccountContractId: contractId ?? null,
      policyContractId: config.contracts.policyContractId ?? null,
      sessionRegistryContractId: config.contracts.sessionRegistryContractId ?? null,
    },
  }
}

async function topUpSmartAccount(agent: Keypair, contractId: string) {
  const transferTx = await AssembledTransaction.build({
    contractId: USDC_TESTNET_CONTRACT_ID,
    method: 'transfer',
    args: [
      nativeToScVal(agent.publicKey(), { type: 'address' }),
      nativeToScVal(contractId, { type: 'address' }),
      nativeToScVal(DEFAULT_TOP_UP_STROOPS.toString(), { type: 'i128' }),
    ],
    networkPassphrase: config.networkPassphrase,
    rpcUrl: config.rpcUrl,
    publicKey: agent.publicKey(),
    parseResultXdr: (result) => result,
  })

  const sent = await transferTx.signAndSend({
    signTransaction: basicNodeSigner(agent, config.networkPassphrase).signTransaction,
  })

  return sent.sendTransactionResponse?.hash ?? null
}

async function main() {
  const env = await loadEnvLocal()
  const existingContractId = env.get('XMPP_SMART_ACCOUNT_CONTRACT_ID')?.trim()

  if (checkOnly) {
    console.log('[xMPP smart-account] preflight check')
    console.log(JSON.stringify(await buildBootstrapStatus(existingContractId ?? null), null, 2))
    return
  }

  if (existingContractId && !force) {
    const agent = getAgentKeypair()
    let topUpHash: string | null = null
    if (shouldFund) {
      topUpHash = await topUpSmartAccount(agent, existingContractId)
    }

    console.log('[xMPP smart-account] using existing smart account contract')
    console.log(
      JSON.stringify(
        {
          contractId: existingContractId,
          reused: true,
          funded: shouldFund,
          topUpTxHash: topUpHash,
          readiness: await buildBootstrapStatus(existingContractId),
        },
        null,
        2,
      ),
    )
    return
  }

  const agent = getAgentKeypair()

  if (dryRun) {
    console.log('[xMPP smart-account] dry run')
    console.log(
      JSON.stringify(
        {
          delegatedSigner: agent.publicKey(),
          thresholdPolicyAddress: config.wallet.thresholdPolicyAddress ?? null,
          spendingLimitPolicyAddress: config.wallet.spendingLimitPolicyAddress ?? null,
          network: config.network,
          rpcUrl: config.rpcUrl,
        },
        null,
        2,
      ),
    )
    return
  }

  const deployed = await deployDelegatedSmartAccount(agent)
  const topUpHash = await topUpSmartAccount(agent, deployed.contractId)
  env.set('XMPP_SMART_ACCOUNT_CONTRACT_ID', deployed.contractId)
  await writeEnvLocal(env)

  console.log('[xMPP smart-account] deployed delegated smart account')
  console.log(
    JSON.stringify(
      {
        contractId: deployed.contractId,
        txHash: deployed.hash,
        topUpTxHash: topUpHash,
        delegatedSigner: agent.publicKey(),
        thresholdPolicyAddress: null,
        spendingLimitPolicyAddress: null,
        note: 'Bootstrap deploy keeps the delegated smart account minimal; policy installation can be layered later.',
        readiness: await buildBootstrapStatus(deployed.contractId),
      },
      null,
      2,
    ),
  )
}

main().catch((error) => {
  console.error('[xMPP smart-account] failed', error)
  process.exit(1)
})
