import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { Keypair } from '@stellar/stellar-sdk'

type BootstrapIdentity = {
  label: string
  secretKey: string
  publicKey: string
}

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const envPath = resolve(repoRoot, '.env')
const envLocalPath = resolve(repoRoot, '.env.local')
const shouldFund = process.argv.includes('--friendbot')
const shouldDeployContracts = process.argv.includes('--contracts')
const shouldSeedContracts = process.argv.includes('--seed-contracts')
const shouldGenerateFeeSponsor = process.argv.includes('--fee-sponsor')
const shouldBootstrapSmartAccount = process.argv.includes('--smart-account')
const dryRun = process.argv.includes('--dry-run')

function parseEnv(text: string) {
  const parsed = new Map<string, string>()
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) {
      continue
    }

    const index = line.indexOf('=')
    if (index === -1) {
      continue
    }

    parsed.set(line.slice(0, index), line.slice(index + 1))
  }

  return parsed
}

async function ensureBaseEnv() {
  if (!existsSync(envPath)) {
    const example = await readFile(resolve(repoRoot, '.env.example'), 'utf8')
    await writeFile(envPath, example, 'utf8')
    console.log('[xMPP bootstrap] created .env from .env.example')
  }
}

async function loadEnvMap() {
  const content = existsSync(envLocalPath) ? await readFile(envLocalPath, 'utf8') : ''
  return parseEnv(content)
}

function ensureIdentity(env: Map<string, string>, keyName: string, label: string): BootstrapIdentity {
  const existingSecret = env.get(keyName)
  const keypair = existingSecret ? Keypair.fromSecret(existingSecret) : Keypair.random()
  env.set(keyName, keypair.secret())
  return {
    label,
    secretKey: keypair.secret(),
    publicKey: keypair.publicKey(),
  }
}

async function friendbotFund(account: BootstrapIdentity) {
  const response = await fetch(
    `https://friendbot.stellar.org/?addr=${encodeURIComponent(account.publicKey)}`,
  )
  if (!response.ok) {
    throw new Error(`Friendbot funding failed for ${account.label}: ${response.status}`)
  }
  console.log(`[xMPP bootstrap] funded ${account.label} ${account.publicKey}`)
}

async function writeEnvLocal(env: Map<string, string>) {
  const lines = ['# Generated by pnpm xmpp:bootstrap']
  for (const [key, value] of [...env.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`${key}=${value}`)
  }
  lines.push('')
  await writeFile(envLocalPath, lines.join('\n'), 'utf8')
}

async function deployContracts(agentSecret: string) {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const child = spawn('bash', ['./contracts/scripts/deploy-testnet.sh', agentSecret], {
      cwd: repoRoot,
      stdio: 'inherit',
      shell: false,
    })
    child.on('exit', (code) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      rejectPromise(new Error(`contract deploy exited with ${code ?? 1}`))
    })
  })
}

async function seedContracts() {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const child = spawn('pnpm', ['exec', 'tsx', 'contracts/scripts/seed-testnet.ts'], {
      cwd: repoRoot,
      stdio: 'inherit',
      shell: false,
    })
    child.on('exit', (code) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      rejectPromise(new Error(`contract seed exited with ${code ?? 1}`))
    })
  })
}

async function bootstrapSmartAccount() {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const args = ['exec', 'tsx', 'scripts/bootstrap-smart-account.ts']
    if (dryRun) {
      args.push('--dry-run')
    }

    const child = spawn('pnpm', args, {
      cwd: repoRoot,
      stdio: 'inherit',
      shell: false,
    })
    child.on('exit', (code) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      rejectPromise(new Error(`smart-account bootstrap exited with ${code ?? 1}`))
    })
  })
}

async function probeSmartAccount() {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const child = spawn('pnpm', ['exec', 'tsx', 'scripts/probe-smart-account-x402.ts'], {
      cwd: repoRoot,
      stdio: 'inherit',
      shell: false,
    })
    child.on('exit', (code) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      rejectPromise(new Error(`smart-account probe exited with ${code ?? 1}`))
    })
  })
}

async function syncContractIds(env: Map<string, string>) {
  const addressesPath = resolve(repoRoot, 'contracts/scripts/addresses.json')
  if (!existsSync(addressesPath)) {
    return
  }

  const addresses = JSON.parse(await readFile(addressesPath, 'utf8')) as {
    policyContractId?: string
    sessionRegistryContractId?: string
  }

  if (addresses.policyContractId) {
    env.set('XMPP_POLICY_CONTRACT_ID', addresses.policyContractId)
  }
  if (addresses.sessionRegistryContractId) {
    env.set('XMPP_SESSION_REGISTRY_CONTRACT_ID', addresses.sessionRegistryContractId)
  }
}

async function main() {
  await ensureBaseEnv()
  const env = await loadEnvMap()

  const agent = ensureIdentity(env, 'XMPP_AGENT_SECRET_KEY', 'agent')
  const facilitator = ensureIdentity(env, 'FACILITATOR_STELLAR_PRIVATE_KEY', 'facilitator')
  const mppServer = ensureIdentity(env, 'MPP_SECRET_KEY', 'mpp-server')

  env.set('X402_RECIPIENT_ADDRESS', env.get('X402_RECIPIENT_ADDRESS') || facilitator.publicKey)
  env.set('MPP_RECIPIENT_ADDRESS', env.get('MPP_RECIPIENT_ADDRESS') || mppServer.publicKey)

  let feeSponsor: BootstrapIdentity | null = null
  if (shouldGenerateFeeSponsor) {
    feeSponsor = ensureIdentity(env, 'XMPP_MPP_FEE_SPONSOR_SECRET_KEY', 'mpp-fee-sponsor')
    env.set('XMPP_ENABLE_MPP_FEE_SPONSORSHIP', 'true')
    env.set('XMPP_ENABLE_MPP_CHARGE_FEE_SPONSORSHIP', 'false')
    env.set('XMPP_ENABLE_MPP_SESSION_FEE_SPONSORSHIP', 'true')
  }

  if (!dryRun) {
    await writeEnvLocal(env)
    console.log('[xMPP bootstrap] wrote .env.local')
  } else {
    console.log('[xMPP bootstrap] dry run only; no files were modified')
  }
  console.log(`[xMPP bootstrap] agent        ${agent.publicKey}`)
  console.log(`[xMPP bootstrap] facilitator  ${facilitator.publicKey}`)
  console.log(`[xMPP bootstrap] mpp-server   ${mppServer.publicKey}`)
  if (feeSponsor) {
    console.log(`[xMPP bootstrap] fee-sponsor ${feeSponsor.publicKey}`)
  }

  if (shouldFund && !dryRun) {
    await friendbotFund(agent)
    await friendbotFund(facilitator)
    await friendbotFund(mppServer)
    if (feeSponsor) {
      await friendbotFund(feeSponsor)
    }
  }

  if (shouldDeployContracts && !dryRun) {
    await deployContracts(agent.secretKey)
    await syncContractIds(env)
    await writeEnvLocal(env)
    await seedContracts()
  }

  if (!dryRun && !shouldDeployContracts) {
    await syncContractIds(env)
    await writeEnvLocal(env)

    if (
      shouldSeedContracts ||
      env.get('XMPP_POLICY_CONTRACT_ID') ||
      env.get('XMPP_SESSION_REGISTRY_CONTRACT_ID')
    ) {
      await seedContracts()
    }
  }

  if (shouldBootstrapSmartAccount) {
    await bootstrapSmartAccount()
    if (!dryRun) {
      await probeSmartAccount()
    }
  }

  console.log('[xMPP bootstrap] next steps:')
  console.log('  pnpm check')
  if (!env.get('XMPP_SMART_ACCOUNT_CONTRACT_ID') && !shouldBootstrapSmartAccount) {
    console.log('  pnpm xmpp:smart-account:bootstrap')
  }
  console.log('  pnpm xmpp:demo:smoke')
}

main().catch((error) => {
  console.error('[xMPP bootstrap] failed', error)
  process.exit(1)
})
